version: "3"

networks:
  backend:
    driver: bridge

volumes:
  mongo:
    driver: local

services:

## Api Node App
    app:
      build: ./
      depends_on:
        - mongo
      environment:
        PORT: 3000
        HOST_PORT: ${HOST_PORT}
        TZ: ${TIMEZONE}
      command: npm run dev
      ports:
        - "${HOST_PORT}:3000"
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      networks:
        - backend
      restart: unless-stopped

### MongoDB ##############################################
    mongo:
      image: mongo:latest
      volumes:
        - ./data/mongo/db:/data/db
        - ./data/mongo/config:/data/configdb
      networks:
        - backend
      restart: unless-stopped
